# Generated by Django 4.1.3 on 2022-11-15 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('short_desc', models.CharField(max_length=150)),
                ('long_desc', models.CharField(max_length=2500)),
                ('location', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=150)),
                ('landmark', models.CharField(max_length=100)),
                ('no_of_bed', models.IntegerField()),
                ('no_of_bath', models.IntegerField()),
                ('no_of_balcony', models.IntegerField()),
                ('furnished', models.BooleanField(default=False)),
                ('carper_area', models.CharField(max_length=10)),
                ('floor', models.CharField(max_length=10)),
                ('transaction_type', models.CharField(max_length=50)),
                ('facing', models.CharField(max_length=10)),
                ('type_of_ownership', models.CharField(max_length=20)),
                ('age_of_construction', models.CharField(max_length=50)),
                ('builder', models.CharField(max_length=30)),
                ('property_for', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell'), ('rent', 'Rent')], default='buy', max_length=10)),
                ('status', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell'), ('rent', 'Rent')], default='buy', max_length=10)),
                ('property_contact', models.CharField(max_length=10)),
                ('posted_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
