# Generated by Django 4.1.3 on 2022-11-15 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0003_alter_property_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('new', 'New'), ('resale', 'Resale')], default='new', max_length=10),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_for',
            field=models.CharField(choices=[('buy', 'Buy'), ('sale', 'Sale'), ('rent', 'Rent')], default='buy', max_length=10),
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('hold', 'Hold'), ('open', 'Open'), ('closed', 'Closed')], default='open', max_length=10),
        ),
    ]
